export interface OfficeProcessAnimationFeatureFlag {
  enabled: boolean;
  progress_bubbles: boolean;
  max_queue_per_actor: number;
  desktop_bubble_limit: number;
  mobile_bubble_limit: number;
  history_replay: boolean;
  effect_level: "high" | "standard" | "low";
}

function envFlag(value: string | undefined, fallback: boolean): boolean {
  if (value === undefined || value.trim() === "") return fallback;
  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) return true;
  if (["0", "false", "no", "off"].includes(normalized)) return false;
  return fallback;
}

function effectLevel(value: string | undefined): "high" | "standard" | "low" {
  const normalized = value?.trim().toLowerCase();
  if (normalized === "low") return "low";
  if (normalized === "standard" || normalized === "medium") return "standard";
  return "high";
}

export function officeProcessAnimationFeatureFlag(env: NodeJS.ProcessEnv = process.env): OfficeProcessAnimationFeatureFlag {
  return {
    enabled: envFlag(env.CODEXPRO_OFFICE_PROCESS_ANIMATION, true),
    progress_bubbles: envFlag(env.CODEXPRO_OFFICE_PROGRESS_BUBBLES, true),
    max_queue_per_actor: 8,
    desktop_bubble_limit: 3,
    mobile_bubble_limit: 1,
    history_replay: envFlag(env.CODEXPRO_OFFICE_HISTORY_REPLAY, true),
    effect_level: effectLevel(env.CODEXPRO_OFFICE_SCENE_EFFECT_LEVEL)
  };
}

export const OFFICE_SCENE_PROCESS_RUNTIME_SCRIPT = String.raw`
      const OFFICE_PROCESS_REPORT_MAP={task_started:{type:"task_received",pose:"standing",priority:60,duration:3600},stage_started:{type:"analysis_started",pose:"sitting",priority:45,duration:5200},progress:{type:"analysis_progress",pose:"sitting",priority:40,duration:4200},assistant_progress:{type:"analysis_progress",pose:null,priority:50,duration:7000,bubble:true},assistant_summary:{type:"finding_published",pose:null,priority:65,duration:12000,bubble:true},finding:{type:"finding_published",pose:null,priority:70,duration:14000,bubble:true},warning:{type:"incident_detected",pose:"incident",priority:92,duration:14000,bubble:true},waiting_user:{type:"waiting_for_user",pose:"hand_raised",priority:100,duration:0,bubble:true},blocked:{type:"incident_detected",pose:"incident",priority:100,duration:0,bubble:true},recovery_started:{type:"recovery_started",pose:"recovering",priority:96,duration:12000,bubble:true},recovery_completed:{type:"recovery_completed",pose:"standing",priority:90,duration:7000,bubble:true},validation_started:{type:"validation_started",pose:"validating",priority:70,duration:6500},validation_passed:{type:"validation_passed",pose:"standing",priority:82,duration:8500,bubble:true},validation_failed:{type:"validation_failed",pose:"incident",priority:98,duration:14000,bubble:true},git_committed:{type:"git_committed",pose:"delivering",priority:82,duration:8500,bubble:true},git_pushed:{type:"git_pushed",pose:"delivering",priority:92,duration:11000,bubble:true},git_failed:{type:"incident_detected",pose:"incident",priority:100,duration:14000,bubble:true},task_completed:{type:"task_completed",pose:"idle",priority:95,duration:8000,bubble:true},task_failed:{type:"incident_detected",pose:"incident",priority:100,duration:0,bubble:true},task_cancelled:{type:"task_archived",pose:"idle",priority:90,duration:7000,bubble:true}};
      function initializeOfficeProcessRuntime(){return {initialized:false,paused:false,projectId:null,queues:new Map(),active:new Map(),timers:new Map(),seen:new Set(),seenOrder:[],actorFingerprints:new Map(),latencies:[],domDurations:[],dropped:0,interrupted:0,failures:0,lastEventAt:null};}
      function officeProcessEnabled(){return officeProcessAnimationFeature?.enabled===true&&!state.scene.reducedMotion;}
      function officeProcessRemember(key){const process=state.scene.process;if(process.seen.has(key))return false;process.seen.add(key);process.seenOrder.push(key);while(process.seenOrder.length>2048){const removed=process.seenOrder.shift();if(removed)process.seen.delete(removed);}return true;}
      function officeProcessIntent(actor,event,semantic){return {intent_id:String(event.feed_key||event.event_id||event.event_kind+":"+event.sequence),event_id:String(event.event_id||event.feed_key||event.sequence),actor_id:actor.actor_id,task_id:actor.task_id,type:semantic.type,pose:semantic.pose,priority:semantic.priority,duration:semantic.duration,summary:sceneReportText(event),sequence:Number(event.sequence||0),event_kind:event.event_kind,severity:event.severity||"info",source_kind:event.source_kind||"task_report",occurred_at:event.occurred_at||new Date().toISOString(),bubble:semantic.bubble===true,state_authority_changed:false};}
      function officeToolOutcomeSemantic(event){const failed=event.status==="failed"||event.status==="blocked";if(failed)return {type:event.tool_category==="validation"?"validation_failed":"incident_detected",pose:"incident",priority:98,duration:14000,bubble:true};switch(event.tool_category){case "read":return {type:"analysis_progress",pose:"sitting",priority:44,duration:4200,bubble:false};case "write":return {type:"write_completed",pose:"typing",priority:74,duration:6200,bubble:false};case "browser":return {type:"browser_interaction",pose:"browsing",priority:70,duration:6200,bubble:false};case "validation":return {type:"validation_passed",pose:"standing",priority:82,duration:8200,bubble:true};case "report":return {type:"finding_published",pose:null,priority:66,duration:11000,bubble:true};case "git":{const phase=String(event.phase||"").toLowerCase();if(phase.includes("prepare"))return {type:"git_prepare",pose:"delivering",priority:78,duration:6200,bubble:false};if(phase.includes("push"))return {type:"git_pushed",pose:"delivering",priority:92,duration:10000,bubble:true};return {type:"git_committed",pose:"delivering",priority:84,duration:8200,bubble:true};}default:return null;}}
      function enqueueOfficeToolOutcomeProcess(event){if(!officeProcessEnabled()||!officeSceneExperienceLive()||!event||event.actor_role==="observer"||event.actor_role==="system")return false;const project=state.scene.process.projectId||selectedToolOutcomeProject();if(!project||event.project_id!==project||!event.actor_id||!state.scene.actors.has(event.actor_id))return false;const semantic=officeToolOutcomeSemantic(event);if(!semantic)return false;return enqueueOfficeProcessIntent({intent_id:"tool:"+event.event_id,event_id:event.event_id,actor_id:event.actor_id,task_id:event.task_id||state.scene.actors.get(event.actor_id)?.actor?.task_id||"",type:semantic.type,pose:semantic.pose,priority:semantic.priority,duration:semantic.duration,summary:String(event.public_summary||event.tool_name||semantic.type).slice(0,120),sequence:Number(event.sequence||0),event_kind:semantic.type,severity:event.status==="failed"?"error":event.status==="blocked"?"warning":event.tool_category==="validation"||semantic.type==="git_pushed"?"success":"info",source_kind:"public_tool_outcome",phase:event.phase||null,occurred_at:event.completed_at||new Date().toISOString(),bubble:semantic.bubble,state_authority_changed:false});}
      function officeSnapshotIntent(actor,revision){let type="analysis_progress",pose=actor.pose||"standing",priority=40,duration=5200;if(actor.writer_active){type="write_started";pose="typing";priority=72;}else if(actor.browser_active){type="browser_interaction";pose="browsing";priority=68;}else if(actor.validation_active){type="validation_started";pose="validating";priority=74;}else if(actor.zone_id==="waiting_user"){type="waiting_for_user";pose="hand_raised";priority=100;duration=0;}else if(actor.zone_id==="incident"){type="incident_detected";pose="incident";priority=100;duration=0;}else if(actor.zone_id==="recovering"){type="recovery_started";pose="recovering";priority=96;duration=12000;}else if(actor.zone_id==="delivery"){type="delivery_ready";pose="delivering";priority=82;duration=8500;}else if(actor.zone_id==="archive"){type="task_completed";pose="idle";priority=90;duration=7000;}return {intent_id:"snapshot:"+revision+":"+actor.actor_id+":"+type,event_id:"snapshot:"+revision,actor_id:actor.actor_id,task_id:actor.task_id,type,pose,priority,duration,summary:String(actor.action||"当前真实任务状态已同步").slice(0,120),sequence:0,event_kind:"snapshot",severity:type==="incident_detected"?"error":"info",source_kind:"visual_snapshot",occurred_at:new Date().toISOString(),bubble:false,state_authority_changed:false};}
      function officeProcessQueue(actorId){let queue=state.scene.process.queues.get(actorId);if(!queue){queue=[];state.scene.process.queues.set(actorId,queue);}return queue;}
      function enqueueOfficeProcessIntent(intent){const process=state.scene.process;if(!officeProcessEnabled()||process.paused||!officeProcessRemember(intent.intent_id))return false;const queue=officeProcessQueue(intent.actor_id),active=process.active.get(intent.actor_id),interrupting=intent.priority>=90;if(active&&interrupting&&intent.priority>=active.priority){clearTimeout(process.timers.get(intent.actor_id));process.timers.delete(intent.actor_id);process.active.delete(intent.actor_id);process.interrupted+=1;finishOfficeProcessIntent(intent.actor_id,active,"interrupted");}queue.push(intent);queue.sort((a,b)=>b.priority-a.priority||a.sequence-b.sequence||a.intent_id.localeCompare(b.intent_id));const limit=Math.max(1,Number(officeProcessAnimationFeature.max_queue_per_actor)||8);while(queue.length>limit){queue.pop();process.dropped+=1;}runOfficeProcessActor(intent.actor_id);return true;}
      function applyOfficeProcessIntent(intent){const started=performance.now(),entry=state.scene.actors.get(intent.actor_id);if(!entry)return false;applyOfficeDeviceFeedback(intent);const node=entry.node;node.dataset.processAction=intent.type;node.dataset.processTone=intent.severity||"info";node.dataset.processSource=intent.source_kind||"unknown";node.classList.add("process-active");if(intent.pose){if(state.scene.movements.has(intent.actor_id))node.dataset.pendingProcessPose=intent.pose;else node.dataset.pose=intent.pose;}node.style.zIndex=String(Math.max(Number(entry.actor.z_index||20),20)+2);if(intent.bubble&&officeProcessAnimationFeature.progress_bubbles)showOfficeProcessBubble(intent);const process=state.scene.process,latency=Math.max(0,Date.now()-Date.parse(intent.occurred_at||new Date().toISOString()));if(Number.isFinite(latency)&&latency<60000){process.latencies.push(latency);if(process.latencies.length>200)process.latencies.shift();}process.domDurations.push(performance.now()-started);if(process.domDurations.length>200)process.domDurations.shift();updateOfficeProcessDiagnostics();return true;}
      function finishOfficeProcessIntent(actorId,intent,reason="completed"){finishOfficeDeviceFeedback(intent);const entry=state.scene.actors.get(actorId);if(entry){entry.node.classList.remove("process-active");delete entry.node.dataset.processAction;delete entry.node.dataset.processTone;delete entry.node.dataset.processSource;delete entry.node.dataset.pendingProcessPose;entry.node.style.zIndex=String(entry.actor.z_index);if(reason!=="interrupted")entry.node.dataset.pose=entry.actor.pose||"idle";}state.scene.process.active.delete(actorId);state.scene.process.timers.delete(actorId);updateOfficeProcessDiagnostics();}
      function runQueuedOfficeProcessActors(){for(const actorId of state.scene.process.queues.keys())runOfficeProcessActor(actorId);}function runOfficeProcessActor(actorId){const process=state.scene.process;if(process.paused||process.active.has(actorId))return;const mobile=window.matchMedia("(max-width: 720px)").matches,activeLimit=mobile?2:6;if(process.active.size>=activeLimit)return;const queue=officeProcessQueue(actorId),intent=queue.shift();if(!intent)return;process.active.set(actorId,intent);process.lastEventAt=intent.occurred_at;try{if(!applyOfficeProcessIntent(intent)){process.active.delete(actorId);return;}}catch{process.failures+=1;process.active.delete(actorId);return;}if(intent.duration<=0){updateOfficeProcessDiagnostics();return;}const timer=setTimeout(()=>{if(process.active.get(actorId)?.intent_id!==intent.intent_id)return;finishOfficeProcessIntent(actorId,intent);runQueuedOfficeProcessActors();},intent.duration);process.timers.set(actorId,timer);}
      function showOfficeProcessBubble(intent){const entry=state.scene.actors.get(intent.actor_id);if(!entry)return;const mobile=window.matchMedia("(max-width: 720px)").matches,limit=mobile?Number(officeProcessAnimationFeature.mobile_bubble_limit||1):Number(officeProcessAnimationFeature.desktop_bubble_limit||3);for(const bubble of entry.node.querySelectorAll(".actor-event-bubble"))bubble.remove();const visible=[...document.querySelectorAll(".actor-event-bubble")];while(visible.length>=limit)visible.shift()?.remove();const bubble=document.createElement("button");bubble.type="button";bubble.className="actor-event-bubble actor-process-bubble";bubble.dataset.processBubble="true";bubble.dataset.sequence=String(intent.sequence||0);bubble.dataset.reportTab=sceneReportTab(intent.event_kind);bubble.dataset.severity=intent.severity||"info";bubble.dataset.eventId=intent.event_id;bubble.dataset.sourceKind=intent.source_kind;const text=document.createElement("span");text.textContent=intent.summary;bubble.append(text);const tech=document.createElement("small");tech.className="technical-only";tech.textContent=(intent.event_id||"event")+" · "+new Date(intent.occurred_at).toLocaleTimeString("zh-CN")+" · "+intent.source_kind;bubble.append(tech);entry.node.prepend(bubble);bubble.addEventListener("click",(event)=>{event.stopPropagation();const objective=findObjective(entry.node.dataset.objectiveKey);if(objective)openReportCenter(objective,Number(intent.sequence||0),sceneReportTab(intent.event_kind));});clearTimeout(state.scene.eventTimers.get(intent.actor_id));const hold=["finding","warning","assistant_summary","validation_failed","task_failed"].includes(intent.event_kind)?14000:7000;const timer=setTimeout(()=>{if(state.scene.eventTimers.get(intent.actor_id)!==timer)return;state.scene.eventTimers.delete(intent.actor_id);bubble.remove();},hold);state.scene.eventTimers.set(intent.actor_id,timer);}
      function syncOfficeSceneProcess(data,visualProject,visibleActors,direct=false){const process=state.scene.process;if(!process||!visualProject||!officeProcessEnabled()||!officeSceneExperienceLive())return;if(process.projectId&&process.projectId!==visualProject.project_id)destroyOfficeProcessRuntime();process.projectId=visualProject.project_id;const actorByTask=new Map((visibleActors||[]).map((actor)=>[actor.task_id,actor]));if(!process.initialized||direct){for(const actor of visibleActors||[])process.actorFingerprints.set(actor.actor_id,[actor.station_id,actor.pose,actor.action,actor.writer_active,actor.browser_active,actor.validation_active].join("|"));process.initialized=true;if(direct){for(const actorId of process.active.keys())finishOfficeProcessIntent(actorId,process.active.get(actorId),"snapshot_resume");process.queues.clear();}updateOfficeProcessDiagnostics();return;}for(const actor of visibleActors||[]){const fingerprint=[actor.station_id,actor.pose,actor.action,actor.writer_active,actor.browser_active,actor.validation_active].join("|"),previous=process.actorFingerprints.get(actor.actor_id);process.actorFingerprints.set(actor.actor_id,fingerprint);if(previous!==undefined&&previous!==fingerprint)enqueueOfficeProcessIntent(officeSnapshotIntent(actor,data.revision));}const events=(Array.isArray(data.activity_feed)?data.activity_feed:[]).filter((event)=>event.project_id===visualProject.project_id&&actorByTask.has(event.task_id)).sort((a,b)=>Date.parse(a.occurred_at||0)-Date.parse(b.occurred_at||0)||Number(a.sequence||0)-Number(b.sequence||0));for(const event of events){const semantic=OFFICE_PROCESS_REPORT_MAP[event.event_kind],actor=actorByTask.get(event.task_id);if(semantic&&actor)enqueueOfficeProcessIntent(officeProcessIntent(actor,event,semantic));}updateOfficeProcessDiagnostics();}
      function setOfficeProcessPaused(paused){const process=state.scene.process;if(!process)return;const next=Boolean(paused);if(process.paused===next)return;process.paused=next;if(next){for(const timer of process.timers.values())clearTimeout(timer);process.timers.clear();return;}process.queues.clear();for(const [actorId,intent] of process.active){finishOfficeProcessIntent(actorId,intent,"visibility_resume");}process.active.clear();if(state.data)updateOfficeScene(state.data,state.viewMode,true);}
      function officeProcessP95(values){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.95))];}function updateOfficeProcessDiagnostics(){const panel=$("officeAnimationDiagnosticsBody"),process=state.scene.process;if(!panel||!process)return;let queued=0;for(const queue of process.queues.values())queued+=queue.length;panel.textContent="人物 "+process.queues.size+" · 主动作 "+process.active.size+" · 排队 "+queued+" · 中断 "+process.interrupted+" · 丢弃 "+process.dropped+" · 失败 "+process.failures+" · 反馈P95 "+Math.round(officeProcessP95(process.latencies))+"ms · DOM P95 "+officeProcessP95(process.domDurations).toFixed(1)+"ms"+(process.lastEventAt?" · 最近 "+new Date(process.lastEventAt).toLocaleTimeString("zh-CN"):"");}
      function installOfficeProcessRuntime(){if(!state.scene.process)state.scene.process=initializeOfficeProcessRuntime();installOfficeSceneExperienceRuntime();updateOfficeProcessDiagnostics();}
      function destroyOfficeProcessRuntime(){destroyOfficeSceneExperienceRuntime();const process=state.scene.process;if(!process)return;for(const timer of process.timers.values())clearTimeout(timer);for(const [actorId,intent] of process.active)finishOfficeProcessIntent(actorId,intent,"destroy");process.queues.clear();process.active.clear();process.timers.clear();process.actorFingerprints.clear();process.seen.clear();process.seenOrder.length=0;process.initialized=false;process.projectId=null;updateOfficeProcessDiagnostics();}
`;
